"""
safeo.erp.decision — Native ERP Risk Decision Log
==================================================
This model is the core of SafeO's ERP integration.

WHY a separate model instead of reusing securec.log?
------------------------------------------------------
securec.log was designed around raw WAF events (input text, patterns).
ERP decisions need a different shape: they track *business context* —
which ERP module was involved, what the business impact was (transaction
blocked / flagged / approved), and which employee or user triggered the
event.  Separating these gives judges a clear model that maps 1:1 to the
ERP theme: Business, Finance, and Workforce.

HOW decisions flow here
-----------------------
1. A CRM lead is saved → crm_lead.py calls /erp/crm/lead on the FastAPI engine
2. The engine returns an ERPDecisionResponse (risk_score, decision, reason, …)
3. The Odoo controller writes one safeo.erp.decision record per action
4. This record is visible in the ERP Decision Log menu and the dashboard
"""

import logging
from odoo import models, fields, api

_logger = logging.getLogger(__name__)


class SafeOERPDecision(models.Model):
    # Naming follows Odoo's dot-notation convention: <module>.<entity>
    _name = 'safeo.erp.decision'
    _description = 'SafeO ERP Risk Decision'
    _order = 'timestamp desc'
    _rec_name = 'display_name'

    # ── Identity ───────────────────────────────────────────────────────────

    # Which ERP workflow was this decision part of?
    erp_module = fields.Selection([
        ('CRM', 'CRM'),
        ('Finance', 'Finance'),
        ('HR', 'HR / Workforce'),
        ('Procurement', 'Procurement'),
        ('Auth', 'Authentication'),
        ('Website', 'Website'),
        ('System', 'System'),
    ], string='ERP Module', required=True, default='System', index=True)

    # Free-form action label e.g. "crm_lead_submission", "finance:payment"
    erp_action = fields.Char(string='Action', required=True)

    # The ERP user or employee who triggered the action
    employee_id = fields.Char(
        string='Employee / User ID',
        help='User or employee identifier passed from the ERP workflow.',
    )
    user_id = fields.Many2one(
        'res.users',
        string='Odoo User',
        ondelete='set null',
        help='Linked Odoo user if the action was taken by a logged-in session.',
    )

    # ── Risk Decision ──────────────────────────────────────────────────────

    # Integer (0-100) for UX clarity; raw float stored separately for ML use
    risk_score = fields.Integer(
        string='Risk Score (0–100)',
        required=True,
        default=0,
        help='Normalised risk score: 0 = no risk, 100 = maximum risk.',
    )
    risk_score_raw = fields.Float(
        string='Risk Score (raw)',
        digits=(3, 3),
        help='Raw float score from the ML engine before integer rounding.',
    )

    # The three decisions mirror the FastAPI ERPDecisionResponse.decision enum
    decision = fields.Selection([
        ('ALLOW', 'Allow — Action Approved'),
        ('WARN', 'Warn — Flagged for Review'),
        ('BLOCK', 'Block — Action Prevented'),
    ], string='Decision', required=True, default='ALLOW', index=True)

    # WHY was this decision made?  Surfaced directly in the ERP UI.
    reason = fields.Text(
        string='Decision Reason',
        help='Human-readable explanation generated by the risk engine.',
    )

    # ── Business Impact ────────────────────────────────────────────────────

    # Maps the technical decision to a business outcome employees understand
    business_impact = fields.Char(string='Business Impact', default='Transaction Approved')

    # Optional: link back to the CRM lead that triggered this decision
    crm_lead_id = fields.Many2one(
        'crm.lead',
        string='CRM Lead',
        ondelete='set null',
        help='Populated when the decision was triggered by a CRM lead save.',
    )

    # ── Detection Details ──────────────────────────────────────────────────

    # Patterns flagged by the ML engine (SQL injection, XSS, etc.)
    detected_patterns = fields.Char(
        string='Detected Patterns',
        help='Comma-separated list of risk patterns found in the input.',
    )

    # Network context at the time of the decision
    network_signal = fields.Selection([
        ('safe', 'Safe'),
        ('risky', 'Risky'),
    ], string='Network Context', default='safe')

    # ── Metadata ───────────────────────────────────────────────────────────

    timestamp = fields.Datetime(
        string='Timestamp',
        default=fields.Datetime.now,
        required=True,
        index=True,
    )

    # API-assigned request ID for tracing back to the FastAPI engine logs
    request_id = fields.Char(string='Request ID')

    # ── Computed fields ────────────────────────────────────────────────────

    display_name = fields.Char(
        string='Display Name',
        compute='_compute_display_name',
        store=True,
    )

    # A simple risk band label for list view colour coding
    risk_level = fields.Selection([
        ('low', 'Low Risk'),
        ('medium', 'Medium Risk'),
        ('high', 'High Risk'),
    ], string='Risk Level', compute='_compute_risk_level', store=True)

    @api.depends('erp_module', 'erp_action', 'decision')
    def _compute_display_name(self):
        for rec in self:
            # Build a human-readable name: "CRM — crm_lead_submission [BLOCK]"
            rec.display_name = f"{rec.erp_module} — {rec.erp_action} [{rec.decision}]"

    @api.depends('risk_score')
    def _compute_risk_level(self):
        for rec in self:
            # Thresholds mirror the FastAPI engine: <30 low, 30-69 medium, ≥70 high
            if rec.risk_score >= 70:
                rec.risk_level = 'high'
            elif rec.risk_score >= 30:
                rec.risk_level = 'medium'
            else:
                rec.risk_level = 'low'

    # ── Class-level helper used by controllers ─────────────────────────────

    @api.model
    def log_erp_decision(self, vals: dict) -> 'SafeOERPDecision':
        """
        Create one ERP decision record from a FastAPI ERPDecisionResponse payload.

        WHY a helper method instead of calling create() directly?
        -  Controllers and model hooks can call this without knowing the field
           mapping — centralises validation and default-setting in one place.
        -  Keeps controller code thin and business logic in the model layer,
           which is the Odoo convention and what the code review checks for.
        """
        patterns = vals.get('detected_patterns', [])
        if isinstance(patterns, list):
            patterns = ', '.join(str(p) for p in patterns)

        record_vals = {
            'erp_module': vals.get('affected_module', 'System'),
            'erp_action': vals.get('action', 'erp_activity'),
            'employee_id': str(vals.get('user_id', '')),
            'risk_score': int(vals.get('risk_score', 0)),
            'risk_score_raw': float(vals.get('risk_score_raw', 0.0)),
            'decision': vals.get('decision', 'ALLOW'),
            'reason': vals.get('reason', ''),
            'business_impact': vals.get('erp_impact', 'transaction_approved'),
            'detected_patterns': patterns,
            'network_signal': vals.get('network_signal', 'safe'),
            'request_id': vals.get('request_id', ''),
            'crm_lead_id': vals.get('crm_lead_id', False),
        }
        return self.sudo().create(record_vals)

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        # Immediate Commit: Force database sync
        self.env.cr.commit()
        return records

    def write(self, vals):
        res = super().write(vals)
        self.env.cr.commit()
        return res

    def unlink(self):
        # Delete Consistency: ensure hard delete syncs immediately
        res = super().unlink()
        self.env.cr.commit()
        return res
